namespace Infusion
{
    public enum Skill
    {
        None = 0,
        Alchemy = 1,
        Anatomy = 2,
        AnimalLore = 3,
        ItemIdentification = 4,
        ArmsLore = 5,
        Parrying = 6,
        Begging = 7,
        Blacksmithing = 8,
        Bowcraft = 9,
        Peacemaking = 10,
        Camping = 11,
        Carpentry = 12,
        Cartography = 13,
        Cooking = 14,
        DetectingHidden = 15,
        DiscordanceEnticement = 16,
        EvaluateIntelligence = 17,
        Healing = 18,
        Fishing = 19,
        ForensicEvaluation = 20,
        Herding = 21,
        Hiding = 22,
        Provocation = 23,
        Inscription = 24,
        Lockpicking = 25,
        Magery = 26,
        ResistingSpells = 27,
        Tactics = 28,
        Snooping = 29,
        Musicianship = 30,
        Poisoning = 31,
        Archery = 32,
        SpiritSpeak = 33,
        Stealing = 34,
        Tailoring = 35,
        AnimalTaming = 36,
        TasteIdentification = 37,
        Tinkering = 38,
        Tracking = 39,
        Veterinary = 40,
        Swordsmanship = 41,
        MaceFighting = 42,
        Fencing = 43,
        Wrestling = 44,
        Lumberjacking = 45,
        Mining = 46,
        Meditation = 47,
        Stealth = 48,
        RemoveTrap = 49,
        Necromancy = 50,
    }
}