<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <AssemblyName>Infusion.Cli</AssemblyName>
    <RuntimeIdentifiers>win-x64;win-arm64;linux-x64;linux-arm64;osx-x64;osx-arm64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Infusion.EngineScripts\Infusion.EngineScripts.csproj" />
    <ProjectReference Include="..\Infusion.LegacyApi\Infusion.LegacyApi.csproj" />
    <ProjectReference Include="..\Infusion.Proxy\Infusion.Proxy.csproj" />
    <ProjectReference Include="..\Infusion\Infusion.csproj" />
  </ItemGroup>

</Project>
