<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>StatusesTestApp</RootNamespace>
    <AssemblyName>StatusesTestApp</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Infusion.LegacyApi\Infusion.LegacyApi.csproj" />
    <ProjectReference Include="..\..\..\..\Infusion\Infusion.csproj" />
    <ProjectReference Include="..\Infusion.Scripts.UOErebor.Extensions\Infusion.Scripts.UOErebor.Extensions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="App.config" />
  </ItemGroup>
</Project>