<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>Infusion.Scripts.UOErebor.Extensions</AssemblyName>
    <RootNamespace>Infusion.Scripts.UOErebor.Extensions</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Infusion.LegacyApi\Infusion.LegacyApi.csproj" />
    <ProjectReference Include="..\..\..\..\Infusion\Infusion.csproj" />
    <ProjectReference Include="..\..\..\..\UltimaSdk\Ultima.csproj" />
  </ItemGroup>
</Project>