<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\version.props" />

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>WinExe</OutputType>
    <ApplicationIcon>infusion.ico</ApplicationIcon>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <Page Remove="AvaloniaApp.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="0.8.0" />
    <PackageReference Include="Avalonia.Desktop" Version="0.8.0" />
    <PackageReference Include="CommandLineParser" Version="2.6.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="1.1.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="2.7.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="2.7.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" Version="2.7.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="2.7.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="2.7.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Features" Version="2.7.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Scripting.Common" Version="2.7.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="2.7.0" />
    <PackageReference Include="Microsoft.Composition" Version="1.0.27" />
    <PackageReference Include="Microsoft.DiaSymReader.Native" Version="1.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="SkiaSharp" Version="1.68.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Infusion.EngineScripts\Infusion.EngineScripts.csproj" />
    <ProjectReference Include="..\Infusion.Injection.Avalonia\Infusion.Injection.Avalonia.csproj" />
    <ProjectReference Include="..\Infusion.LegacyApi\Infusion.LegacyApi.csproj" />
    <ProjectReference Include="..\RoslynPad\src\RoslynPad.Common.UI\RoslynPad.Common.UI.csproj" />
    <ProjectReference Include="..\RoslynPad\src\RoslynPad.Common\RoslynPad.Common.csproj" />
    <ProjectReference Include="..\RoslynPad\src\RoslynPad.Editor.Windows\RoslynPad.Editor.Windows.csproj" />
    <ProjectReference Include="..\RoslynPad\src\RoslynPad.Roslyn.Windows\RoslynPad.Roslyn.Windows.csproj" />
    <ProjectReference Include="..\RoslynPad\src\RoslynPad\RoslynPad.csproj" />
    <ProjectReference Include="..\Infusion.Proxy\Infusion.Proxy.csproj" />
    <ProjectReference Include="..\Infusion\Infusion.csproj" />
    <ProjectReference Include="..\UltimaSdk\Ultima.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="infusion.png" />
    <Resource Include="infusion.ico" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="AvaloniaApp.xaml">
      <SubType>Designer</SubType>
    </AvaloniaResource>
    <Compile Update="AvaloniaApp.xaml.cs">
      <DependentUpon>AvaloniaApp.xaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>